### ISSUE TITLE
Pay To Many broken

### ISSUE THREAD

**Issue by Praesidiarius** [Electrum-RVN-SIG/electrum-ravencoin#10]
I use electrum-rvn-0.2.2-11-g6be8045-dirty-x86_64 on kali linux for a while now, to make my faucet payments. i need electrum because of the paytomany function. i have a CVS, what i copy to the "Pay to" window.

In the new 0.3.0 version from this repo (electrum-ravencoin-0.3.0-r2.AppImage),
 the pay to many is not working anymore. i always get error
"Invalid Lines found:" and then it lists all the addresses. here is an example:

`R9vJFUvdZqmYAPwYAfT4tqayioahPvEbQf,1.06470833
RUz33T5uF9H2YQEorCiCJvpHjDdeBW58AF,0.84129268
RGAAPaPmV4n7ZCeteAsYeiee9pwjwxqT3h,1.64042834
RDekG9wLUJq2B86PJFNErPUANjnx9MPwrK,1.37375772`

Would be awesome if that could be fixed, i am coder myself (sadly only nodejs/php/) so i cannot fix it on my own, but i will provide any information you need and willing to help to fix the bug. i would also contribute some raven if its fixed, as i really need the wallet.

If you need any more information or screenshots just let me know.

**Comment by kralverde** [comment]
Tracking. Thank you!

**Comment by kralverde** [comment]
Patched in https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/0380c7d327d0e2215a4803918b7a6b7e24505ec1
Will close this issue once public testing of 0.4.0 ends.

**Comment by Praesidiarius** [comment]
![grafik](https://user-images.githubusercontent.com/24601980/124392979-8e293f00-dcf8-11eb-91b9-44ddbdeb682b.png)

i tried using 0.4.0 test version. as i open the "Send" Tab, i get this error multiple times 
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?

**Comment by kralverde** [comment]
I'm not getting this error on my end.
Would you mind try running again with the -v parameter to get a more verbose information?

**Comment by Praesidiarius** [comment]
there you go. the test was with 0.4.0-r1 from this page (tested with 0.4.0 and 0.4.0-r1 its the same error for me)
https://github.com/kralverde/electrum-ravencoin-utd/releases

[rvndebug.log](https://github.com/Electrum-RVN-SIG/electrum-ravencoin/files/6765932/rvndebug.log)

**Comment by kralverde** [comment]
Does this fix the bug?
https://github.com/kralverde/electrum-ravencoin-utd/releases/tag/v0.4.0.1.1

**Comment by Praesidiarius** [comment]
![grafik](https://user-images.githubusercontent.com/24601980/124514453-5647f780-dddd-11eb-8520-7fcd5ff9241a.png)

uuuuu nice, yes it does. also the error has gone for the pay to many. seems to work now. i will test with the next payment run in some hours if it really does send correctly, but i now get to the "enter password" screen with no more parsing error :)


Very nice, thanks a lot.
you have some rvn address i can donate?

**Comment by kralverde** [comment]
Glad to hear!
RDRczYCUeLwXVnrKMYHKYLS1oPc9aCxGnG

**Comment by Praesidiarius** [comment]
i have just tested paytomany for sending Raven and also paytomany for sending assets (SWISSFAUCET). 

very, very nice! Now i can make batch payments for my token payments with csv - awesome :)

keep on the good work! thanks a lot
