### ISSUE TITLE
Version 0.4.0 yields invalid status 6702 with Ledger Nano

### ISSUE THREAD

**Issue by williamblevins** [Electrum-RVN-SIG/electrum-ravencoin#21]
Using the Windows binary.

**Comment by dramirezRT** [comment]
Hello, when is this happening? What is the scenario/steps followed to reproduce?

**Comment by williamblevins** [comment]
Windows 10
electrum-ravencoin-0.4.0.exe
next -> next -> hardware wallet

**Comment by williamblevins** [comment]
Just follow here: https://ravencoin.org/ledger/

**Comment by kralverde** [comment]
would you mind sending the log file for this error?

**Comment by williamblevins** [comment]
I'm not aware that any log file is created.

```
No hardware device detected.
To trigger a rescan, press 'Next'.

If your device is not detected on Windows, go to "Settings", "Devices", "Connected devices", and do "Remove device". Then, plug your device again.
While this is less than ideal, it might help if you run Electrum as Administrator.


Debug message
  ledger: (error getting device infos)
    Exception : Invalid status 6702
```

**Comment by williamblevins** [comment]
Ledger Nano S
Firmware `2.0.0`

**Comment by williamblevins** [comment]
Ledger Ravencoin (RVN) app version 1.6.3 (latest).

**Comment by williamblevins** [comment]
I never get the "Allow XYZ app" on the ledger device. That may be an indication.

**Comment by kralverde** [comment]
do you have any other applications open when attempting to open electrum (such as ledger live)?

**Comment by williamblevins** [comment]
I've tried both ways. Ledger live closed and open. Same result. In the closed case, no application is "connected" and/or "allowed" by the device. Only 1 device is connected.

**Comment by williamblevins** [comment]
Ok, so embarassingly, I realized that I had to select enter application on the ledger for it to be available. This didn't work in the same way are some other applications which use a request model. Thanks!
