### ISSUE TITLE
Error in Sync Transactions - Wallet stops responding

### ISSUE THREAD

**Issue by higorpereira** [Electrum-RVN-SIG/electrum-ravencoin#23]
Hi, I use Electrum Wallet integrated with my ledger, and it is not synchronizing transactions.

LOG:
------
Traceback (most recent call last):
  File "electrum\util.py", line 1252, in wrapper
  File "electrum\interface.py", line 487, in wrapper_func
  File "electrum\interface.py", line 510, in run
  File "electrum\interface.py", line 642, in open_session
  File "aiorpcx\rawsocket.py", line 166, in __aenter__
  File "electrum\interface.py", line 254, in create_connection
  File "aiorpcx\rawsocket.py", line 163, in create_connection
  File "asyncio\base_events.py", line 820, in create_connection
  File "asyncio\base_events.py", line 846, in _create_connection_transport
  File "asyncio\selector_events.py", line 714, in _read_ready
MemoryError
20210814T030351.587605Z |     INFO | network | couldn't launch iface electrum3.rvn.rocks:50002:s -- CancelledError()
20210814T030401.990329Z |     INFO | network | connecting to electrum3.rvn.rocks:50002:s as new interface
20210814T030402.372270Z |    ERROR | interface.[electrum3.rvn.rocks:50002] | Exception in run: MemoryError()

**Comment by kralverde** [comment]
Do you mine to your ledger? How many incoming transactions do you have on it?

**Comment by higorpereira** [comment]
Yes, I have mine directly to the wallet address. The number of transactions is a little high...

**Comment by kralverde** [comment]
okay... this is a problem with the base bitcoin electrum as well... there are so many transactions and verifications that the memory becomes depleted.

To do now:
Stop mining to hardware! Even when everything is synced, the amount of transactions will likely mean it will take days to send all of your RVN due to hardware limitations. I would recommend mining to a software wallet and then transferring that to your ledger after a certain amount of time.

Create a temporary swap file to "increase" your memory. After your wallet is synchronized your verified transaction information will be written to file and your can safely remove that swap file.

After syncing you might come into an issue where there are too many inputs when trying to send. Go to view > show coins, select 20 or so, and choose spend coins to spend only those for inputs.

In the future:
I will try to get batching verification requests and having periodic file writes to avoid this issue in edge cases like yours in the next major update (probably 2ish months).

**Comment by higorpereira** [comment]
I understand. Any idea how to create this "swap file" on Windows?

And.. thank you for your help, and thanks for the work you do here :)

**Comment by kralverde** [comment]
You'll need to google that yourself. I'm also unsure of how many GB you'd need to add...

**Comment by higorpereira** [comment]
Would setting up a personal electrumx server help in any way here? I put more than 10Gb in swap file and I keep being disconnected...

--------
20210814T191606.464533Z |     INFO | interface.[rvn4lyfe.com:50002] | disconnecting due to: ConnectError(ConnectionRefusedError(10061, "Connect call failed ('51.222.139.25', 50002)"),)
20210814T191606.465533Z |     INFO | network | couldn't launch iface rvn4lyfe.com:50002:s -- CancelledError()
20210814T191608.286838Z |     INFO | network | connecting to ravennode-02.beep.pw:50002:s as new interface
20210814T191609.256732Z |     INFO | interface.[ravennode-02.beep.pw:50002] | connection established. version: ['ElectrumX Ravencoin 1.9', '1.4']
20210814T191609.435627Z |     INFO | interface.[ravennode-02.beep.pw:50002] | set blockchain with height 1885656
20210814T191609.436626Z |     INFO | interface.[ravennode-02.beep.pw:50002] | skipping header 1885656
20210814T191609.437625Z |     INFO | network | switching to ravennode-02.beep.pw:50002:s
20210814T191609.682519Z |     INFO | network | fee_histogram [[11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000], [11, 10000000]]
20210814T191609.683523Z |     INFO | network | fee_estimates {25: 1000000, 10: 1000000, 5: 1000000, 2: 1000000}
20210814T191610.826866Z |    ERROR | interface.[ravennode-02.beep.pw:50002] | Exception in wrapper_func: MemoryError()
Traceback (most recent call last):
  File "electrum\util.py", line 894, in wrapper
  File "electrum\interface.py", line 331, in wrapper_func
  File "electrum\interface.py", line 355, in run
  File "electrum\interface.py", line 462, in open_session
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 81, in _start_tasks
  File "site-packages\aiorpcx\curio.py", line 242, in __aexit__
  File "site-packages\aiorpcx\curio.py", line 211, in join
  File "electrum\synchronizer.py", line 262, in main
  File "electrum\wallet.py", line 246, in set_up_to_date
  File "electrum\util.py", line 356, in <lambda>
  File "electrum\util.py", line 352, in do_profile
  File "electrum\storage.py", line 89, in write
  File "electrum\storage.py", line 98, in _write
  File "electrum\json_db.py", line 86, in wrapper
  File "electrum\json_db.py", line 120, in dump
  File "json\__init__.py", line 238, in dumps
  File "json\encoder.py", line 201, in encode
MemoryError

**Comment by kralverde** [comment]
unfortunately this is all client side. Maybe just try reopening the client periodically. Some of the verified transactions *should* be saved each time it memfaults

(Did it sync more with the swap file?)

**Comment by klinge-wat** [comment]
Hi, I have unfortunately the same problem. But to increase the pagefile in Windows 10, does not help. If Iam looking in the Task-Manager it seems, that the memory error comes on round about 3.5 GB RAM reservation and collaps then to 2.9 GB. I have 16 GB RAM and only 57 % are in use. Is it possible that the software "Electrum" with 32bit can adress only 4 GB RAM? For a good advise I would be very greatful!

**Comment by klinge-wat** [comment]
> Hallo, ich habe leider das gleiche Problem. Aber die Auslagerungsdatei in Windows 10 zu erhöhen, hilft nicht. Wenn ich in den Task-Manager schaue, scheint es, dass der Speicherfehler bei etwa 3,5 GB RAM-Reservierung auftritt und dann auf 2,9 GB zusammenbricht. Ich habe 16 GB RAM und nur 57 % sind belegt. Kann es sein, dass die Software "Electrum" mit 32bit nur 4 GB RAM adressieren kann? Für eine gute Beratung wäre ich sehr dankbar!

No help?

**Comment by kralverde** [comment]
There is nothing right now, you will need to use the core for such large transaction histories until further notice

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v0.4.6 can implement optional parameters --nosave and --noverify ... this is not recommended for normal usage and will cause some bugs, but will aid with this issue
