### ISSUE TITLE
Installs as electrum, not electrum-ravencoin

### ISSUE THREAD

**Issue by Laurenumnom** [Electrum-RVN-SIG/electrum-ravencoin#29]
Entry in ~/.local/bin/ does not match instructions or provided .desktop

**Comment by kralverde** [comment]
I can't recreate on my end, probably have something cached. Would you mind telling me what you ran so I can take a better look later?

**Comment by Laurenumnom** [comment]
I doubt it's something cached but could be something else on my end.
```sudo pacman -Syu
sudo pacman -S python-cryptography python-pyqt5 libsecp256k1 python-pip
git clone https://github.com/Electrum-RVN-SIG/electrum-ravencoin.git
cd electrum-ravencoin
sudo pip install virtualenv
pip install --user -e .
```
I just tried this again with a freshly installed laptop and had the same results. Only difference on laptop is that I had to also install python-wheel and base-devel but inspecting ~/.local/bin/ had the same electrum instead of electrum-ravencoin. It's not a huge issue, more like an inconvenience.

**Comment by kralverde** [comment]
Ah I meant to say something was off on my end -- I'll check it out soon. Thank you.

**Comment by kralverde** [comment]
Hi again, thanks for letting me know about this; looks like I forgot to push a file rename on the initial commit. Would you mind pulling the latest and making sure its good?

**Comment by Laurenumnom** [comment]
It's installing now as electrum-ravencoin, thank you. Icon is still missing for .desktop entry in appmenu though.

**Comment by kralverde** [comment]
did you run `sudo desktop-file-install electrum-ravencoin.desktop` ?

**Comment by Laurenumnom** [comment]
Yes, that is what I ran as instructed inside the file to make it into applist

**Comment by kralverde** [comment]
OK I'll reopen this as a reminder to check that out too. thanks again

**Comment by kralverde** [comment]
Just confirming this is what you mean by applist (please excuse the ubuntu)
![Screenshot from 2021-11-05 22-40-24](https://user-images.githubusercontent.com/80051564/140595260-c67b0868-d1b3-4815-b82a-26f4a20ba88c.png)

**Comment by Laurenumnom** [comment]
No need to excuse, Ubuntu and Gnome are both great!
That is indeed what I meant, I'm using XFCE desktop so it's a bit more classical but effectively the same thing. (Don't mind the correct icon on panel, it is manually set for my sanity)
![image](https://user-images.githubusercontent.com/6765454/140613015-e6e92acf-dda3-4f5c-b3fb-d281e0ff5609.png)
