### ISSUE TITLE
Opened wallet file from .2.2 with .3.0 and now it I can no longer access my Nano S.

### ISSUE THREAD

**Issue by slapshotkc** [Electrum-RVN-SIG/electrum-ravencoin#3]
What to I do?

**Comment by OversizedWizard** [comment]
I couldn't even open my wallet from 0.2.2.

I ended up creating a new wallet using my ledger nano x.
Create a new receive address.

Then open 0.2.2 with existing wallet and send all funds from your 2.2 wallet over to new 0.3.0 receive address.

But then all of a sudden, all my transactions from my wallet 0.2.2 showed up in new version!!! 
And my old receive address isn't showing in 0.3.0 version but it's still receiving from foxypool using that old address.
Does this mean that address is locked to ledger or something?

**Comment by kralverde** [comment]
Everything is tied to your ledger device so your funds are safe. You can create a new wallet with it if you need to. Seems to be a problem upgrading wallet files. There should be log files in your electrum folder would you mind posting the error here?

**Comment by slapshotkc** [comment]
[electrum_log_20210608T211727Z_12060.log](https://github.com/Electrum-RVN-SIG/electrum-ravencoin/files/6642959/electrum_log_20210608T211727Z_12060.log)

**Comment by kralverde** [comment]
I see the problem, thank you for the help. This will be fixed in the next update. For now creating a "new" wallet again with your ledger or re-entering your seed words if its a software wallet will allow to make the jump from 0.2.2 to 0.3.0

**Comment by kralverde** [comment]
Closed in favor of https://github.com/Electrum-RVN-SIG/electrum-ravencoin/issues/4

**Comment by slapshotkc** [comment]
OK.  Sorry, I'm a bit new to all of this. So my old wallet is no longer accessible and all the coin in it is gone?
