### ISSUE TITLE
No network connection!

### ISSUE THREAD

**Issue by eavi12** [Electrum-RVN-SIG/electrum-ravencoin#30]
I just installed Electrum Raven 0.4.4 and I am using it with a ledger. However none of the default servers are connecting to any of the nodes. Any recommendations? Thank you in advanced.
![ElecRVN](https://user-images.githubusercontent.com/58631054/140433572-f41f6b1a-aa49-4f04-bc25-496dde8e9d6c.jpg)

**Comment by Okin00** [comment]
I have the same problem.

**Comment by Okin00** [comment]
Everything is already working miraculously.

**Comment by eavi12** [comment]
Still no go for me. It just started connecting on your end?

**Comment by anotherhabit** [comment]
I had the same issue. 

I noticed that my public ip address was different than in the config file. Manually changed it in the config file and it immediatly connected when I reopend the wallet.

Hope this also gives you success. I suspect my issue was caused by an uplanned power outage.

**Comment by FB71FB** [comment]
Still not working for me

**Comment by FB71FB** [comment]
Estimation time until completion 11154 days, 14:40:10

**Comment by FB71FB** [comment]
0211105T171133.056246Z |     INFO | interface.[157.90.24.103:8767] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionResetError(),),)
20211105T171133.056246Z |     INFO | network | couldn't launch iface 157.90.24.103:8767:s -- CancelledError()

**Comment by eavi12** [comment]
I added my public ip to the config file and it seems to be working.

**Comment by FB71FB** [comment]
this is my config file where can i add my public ip  thanks 
{
    "auto_connect": true,
    "blockchain_preferred_block": {
        "hash": "0000006b444bc2f2ffe627be9d9e7e7a0730000870ef6eb6da46c8eae389df90",
        "height": 0
    },
    "check_updates": true,
    "config_version": 3,
    "gui_last_wallet": "********************",
    "io_dir": "****r",
    "is_maximized": false,
    "nosegwit": true,
    "oneserver": false,
    "recently_open": [
        "g:\\*****",
        "g:\\*******
    ],
    "rpcpassword": "*************************************",
    "rpcuser": "***",
    "server": "157.90.24.103:8767:s",
    "show_addresses_tab": true
}

**Comment by kralverde** [comment]
There was a ddos on the servers

**Comment by FB71FB** [comment]
an attack ?????
connection route in Tunisia at 00:00 
thanks
