### ISSUE TITLE
No sychronization with nodes 

### ISSUE THREAD

**Issue by FB71FB** [Electrum-RVN-SIG/electrum-ravencoin#31]
Opening my Wallet an endless synchronization and no connection

**Comment by FB71FB** [comment]
0211105T171133.056246Z |     INFO | interface.[157.90.24.103:8767] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionResetError(),),)
20211105T171133.056246Z |     INFO | network | couldn't launch iface 157.90.24.103:8767:s -- CancelledError()

**Comment by kralverde** [comment]
There was a ddos on the servers
