### ISSUE TITLE
DMG won't work

### ISSUE THREAD

**Issue by willnix86** [Electrum-RVN-SIG/electrum-ravencoin#32]
When i try and use the Mac DMG, I'm blocked by laptop Security stuff. If I go into security settings and click 'open anyway', the app launches and then shuts immediately. I'm then unable to eject the dmg

**Comment by jonnevin** [comment]
same issue here

**Comment by kralverde** [comment]
If you try to make the binary yourself as per https://github.com/Electrum-RVN-SIG/electrum-ravencoin/blob/master/contrib/osx does it still fail to execute?

**Comment by brianwfreeman** [comment]
I experienced the same bug as well. DMG will not run on Mac.

**Comment by erngck** [comment]
Same bug continues

**Comment by kralverde** [comment]
Once again, If you try to make the binary yourself as per https://github.com/Electrum-RVN-SIG/electrum-ravencoin/blob/master/contrib/osx does it still fail to execute?
