### ISSUE TITLE
Cannot connect to any server

### ISSUE THREAD

**Issue by HendrikLanghammer** [Electrum-RVN-SIG/electrum-ravencoin#33]
I've seen there is already 2 issues closed 11 days ago. I try connecting for days without success. I try with and without Tor proxy. Is there another issue? Can there be put more servers into the Network screen?

Some excerpts from my log:

20211116T164620.692812Z |     INFO | interface.[electrum.ravencoin.foundation:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(SOCKSFailure('connection refused',),)

20211116T164649.448367Z |     INFO | interface.[electrum2.rvn.rocks:50002] | disconnecting due to: ConnectError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)

20211116T164741.165123Z |     INFO | interface.[electrum.ravencoin.foundation:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('128.199.15.190', 50002)"),),)

20211116T164910.218487Z |     INFO | interface.[rvn4lyfe.com:50002] | disconnecting due to: ConnectError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)

20211116T164931.104607Z |     INFO | interface.[electrum3.rvn.rocks:50002] | disconnecting due to: ConnectError(TimeoutError(10060, "Connect call failed ('195.201.20.56', 50002)"),)

20211116T165213.170114Z |     INFO | network | connecting to electrum-rvn.dnsalias.net:50002:s as new interface
20211116T165214.556051Z |     INFO | interface.[electrum-rvn.dnsalias.net:50002] | succeeded in getting cert
20211116T165215.296228Z |     INFO | interface.[electrum-rvn.dnsalias.net:50002] | disconnecting due to GracefulDisconnect(RPCError(1, 'unsupported protocol version: 1.9'),)

**Comment by kralverde** [comment]
It looks like you are using an old version correct?

**Comment by HendrikLanghammer** [comment]
Version I use is freshly installed latest release Electrum Ravencoin 0.4.4

**Comment by kralverde** [comment]
Go into your electrum directory and delete your certs in the certs folder

**Comment by HendrikLanghammer** [comment]
That did the trick for electrum1.rvn.rocks, electrum2.rvn.rocks and rvn4lyfe.com, thanks!
