### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by chk777** [Electrum-RVN-SIG/electrum-ravencoin#35]

**Comment by kralverde** [comment]
could you send whats in your log file? you can find you electrum folder location by typing wheres_my_stuff() in the console

**Comment by kralverde** [comment]
https://github.com/spesmilo/electrum/issues/6684

or try running electrum without any trezor background apps

**Comment by chk777** [comment]
I ran electrum differently and suite in and without suite

**Comment by chk777** [comment]
`ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('128.199.15.190', 

50002)"),),)
20220107T181650.528816Z |     INFO | network | couldn't launch iface electrum.ravencoin.foundation:50002:s -- 

CancelledError()
20220107T181652.226912Z |     INFO | plugin.DeviceMgr | scanning devices...
20220107T181652.537930Z |    DEBUG | util.profiler | DeviceMgr.scan_devices 0.3110
20220107T181708.509844Z |     INFO | interface.[electrum3.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('195.201.20.56', 50002)"),)
20220107T181708.524845Z |     INFO | network | couldn't launch iface electrum3.rvn.rocks:50002:s -- CancelledError()
20220107T181708.569847Z |    DEBUG | util.profiler | WalletDB._load_transactions 2.7932
20220107T181708.575848Z |    DEBUG | util.profiler | AddressSynchronizer.load_local_history 0.0010
20220107T181708.577848Z |    DEBUG | util.profiler | AddressSynchronizer.check_history 0.0010
20220107T181708.787860Z |     INFO | interface.[electrum1.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('94.130.98.255', 50002)"),)
20220107T181708.788860Z |     INFO | network | couldn't launch iface electrum1.rvn.rocks:50002:s -- CancelledError()
20220107T181708.829862Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181708.836863Z |     INFO | wallet.Standard_Wallet.[default_wallet] | set_up_to_date: True
20220107T181709.052875Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181712.374065Z |     INFO | storage.WalletStorage | saved z:\raven\electrum_ravencoin_data\wallets

\default_wallet
20220107T181712.381065Z |    DEBUG | util.profiler | WalletDB._write 3.5442
20220107T181712.399066Z |     INFO | interface.[rvn-dashboard.com:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('51.210.111.237', 50002)"),)
20220107T181712.407067Z |     INFO | network | couldn't launch iface rvn-dashboard.com:50002:s -- CancelledError()
20220107T181712.964099Z |    DEBUG | util.profiler | MessageList.update 0.0000
20220107T181713.344120Z |     INFO | plugin.DeviceMgr | scanning devices...
20220107T181713.384123Z |    DEBUG | util.profiler | 

Deterministic_Wallet.try_detecting_internal_addresses_corruption 0.0440
20220107T181713.384123Z |    DEBUG | util.profiler | ElectrumWindow.load_wallet 0.1540
20220107T181713.387123Z |     INFO | gui.qt.ElectrumGui | starting Qt main loop
20220107T181713.464127Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181713.515130Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.0490
20220107T181713.539132Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0750
20220107T181713.554132Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181713.554132Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181713.667139Z |    DEBUG | util.profiler | DeviceMgr.scan_devices 0.3230
20220107T181713.668139Z |     INFO | plugin.DeviceMgr | getting client for keystore
20220107T181714.071162Z |     INFO | plugin.DeviceMgr | end client for keystore
20220107T181714.074162Z |     INFO | plugin.DeviceMgr | getting client for keystore
20220107T181714.098163Z |     INFO | plugin.DeviceMgr | end client for keystore
20220107T181717.887380Z |     INFO | gui.qt.update_checker.UpdateCheckThread | valid sig for version announcement 

'0.4.0' from address 'RPuQNvDVBC5Q4fXKyfYLjrunbyqiEYckP5'
20220107T181720.239515Z |     INFO | interface.[electrum.ravencoin.foundation:50002] | disconnecting due to: 

ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('128.199.15.190', 

50002)"),),)
20220107T181720.246515Z |     INFO | network | couldn't launch iface electrum.ravencoin.foundation:50002:s -- 

CancelledError()
20220107T181737.865523Z |     INFO | interface.[electrum3.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('195.201.20.56', 50002)"),)
20220107T181737.874523Z |     INFO | network | couldn't launch iface electrum3.rvn.rocks:50002:s -- CancelledError()
20220107T181739.169597Z |     INFO | interface.[rvn-dashboard.com:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('51.210.111.237', 50002)"),)
20220107T181739.183598Z |     INFO | network | couldn't launch iface rvn-dashboard.com:50002:s -- CancelledError()
20220107T181739.349608Z |     INFO | interface.[electrum1.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('94.130.98.255', 50002)"),)
20220107T181739.358608Z |     INFO | network | couldn't launch iface electrum1.rvn.rocks:50002:s -- CancelledError()
20220107T181744.247888Z |     INFO | interface.[electrum2.rvn.rocks:50002] | could connect 2094522
20220107T181744.743916Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181744.863923Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.1190
20220107T181744.891925Z |    DEBUG | util.profiler | HistoryModel.refresh 0.1480
20220107T181744.911926Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181744.919926Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181744.981930Z |     INFO | interface.[aethyn.com:50002] | skipping header 2094522
20220107T181745.258946Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181745.377953Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.1180
20220107T181745.381953Z |    DEBUG | util.profiler | HistoryModel.refresh 0.1230
20220107T181745.403954Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181745.404954Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181748.311120Z |     INFO | interface.[rvn4lyfe.com:50002] | skipping header 2094522
20220107T181748.756146Z |     INFO | network | fee_histogram []
20220107T181748.803149Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181748.912155Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.1080
20220107T181748.918155Z |    DEBUG | util.profiler | HistoryModel.refresh 0.1150
20220107T181748.935156Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181748.936156Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181749.355180Z |     INFO | network | fee_estimates {25: 1017944, 10: 1017944, 5: 1017944, 2: 4978197}
20220107T181808.571279Z |     INFO | interface.[rvn4lyfe.com:50002] | could connect 2094523
20220107T181809.080308Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181809.218316Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.1360
20220107T181809.275320Z |    DEBUG | util.profiler | HistoryModel.refresh 0.1950
20220107T181809.299321Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181809.300321Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181809.330323Z |     INFO | interface.[electrum2.rvn.rocks:50002] | skipping header 2094523
20220107T181809.727345Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181809.910356Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.1820
20220107T181809.913356Z |    DEBUG | util.profiler | HistoryModel.refresh 0.1860
20220107T181809.932357Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181809.933357Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181810.198372Z |     INFO | interface.[aethyn.com:50002] | skipping header 2094523
20220107T181810.615396Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T181810.744403Z |    DEBUG | util.profiler | Abstract_Wallet.get_full_history 0.1270
20220107T181810.748404Z |    DEBUG | util.profiler | HistoryModel.refresh 0.1330
20220107T181810.767405Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181810.768405Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T181820.918985Z |     INFO | interface.[electrum.ravencoin.foundation:50002] | disconnecting due to: 

ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('128.199.15.190', 

50002)"),),)
20220107T181820.926986Z |     INFO | network | couldn't launch iface electrum.ravencoin.foundation:50002:s -- 

CancelledError()
20220107T181837.937959Z |     INFO | interface.[electrum3.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('195.201.20.56', 50002)"),)
20220107T181837.943959Z |     INFO | network | couldn't launch iface electrum3.rvn.rocks:50002:s -- CancelledError()
20220107T181839.784065Z |     INFO | interface.[electrum1.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('94.130.98.255', 50002)"),)
20220107T181839.786065Z |     INFO | network | couldn't launch iface electrum1.rvn.rocks:50002:s -- CancelledError()
20220107T181839.907072Z |     INFO | interface.[rvn-dashboard.com:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('51.210.111.237', 50002)"),)
20220107T181839.909072Z |     INFO | network | couldn't launch iface rvn-dashboard.com:50002:s -- CancelledError()
20220107T181848.791580Z |     INFO | network | fee_histogram []
20220107T181918.321269Z |     INFO | exchange_rate.CoinGecko | getting fx quotes for USD
20220107T181918.991307Z |     INFO | exchange_rate.CoinGecko | received fx quotes
20220107T181919.003308Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T181948.839014Z |     INFO | network | fee_histogram []
20220107T182021.119860Z |     INFO | interface.[electrum.ravencoin.foundation:50002] | disconnecting due to: 

ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('128.199.15.190', 

50002)"),),)
20220107T182021.123861Z |     INFO | network | couldn't launch iface electrum.ravencoin.foundation:50002:s -- 

CancelledError()
20220107T182038.974882Z |     INFO | interface.[electrum3.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('195.201.20.56', 50002)"),)
20220107T182038.981882Z |     INFO | network | couldn't launch iface electrum3.rvn.rocks:50002:s -- CancelledError()
20220107T182040.031942Z |     INFO | interface.[electrum1.rvn.rocks:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('94.130.98.255', 50002)"),)
20220107T182040.033942Z |     INFO | network | couldn't launch iface electrum1.rvn.rocks:50002:s -- CancelledError()
20220107T182040.180951Z |     INFO | interface.[rvn-dashboard.com:50002] | disconnecting due to: ConnectError

(TimeoutError(10060, "Connect call failed ('51.210.111.237', 50002)"),)
20220107T182040.188951Z |     INFO | network | couldn't launch iface rvn-dashboard.com:50002:s -- CancelledError()
20220107T182048.857447Z |     INFO | network | fee_histogram []
20220107T182148.966885Z |     INFO | network | fee_histogram []
20220107T182148.988887Z |     INFO | exchange_rate.CoinGecko | getting fx quotes for USD
20220107T182154.640210Z |     INFO | exchange_rate.CoinGecko | received fx quotes
20220107T182154.646210Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T182159.255474Z |     INFO | interface.[rvn4lyfe.com:50002] | could connect 2094524
20220107T182159.450485Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T182159.451485Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0010
20220107T182159.481487Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T182159.482486Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T182159.898510Z |     INFO | interface.[electrum2.rvn.rocks:50002] | skipping header 2094524
20220107T182159.959514Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T182159.960514Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0010
20220107T182159.982515Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T182159.983515Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T182200.790561Z |     INFO | interface.[aethyn.com:50002] | skipping header 2094524
20220107T182200.956571Z |     INFO | gui.qt.history_list.HistoryModel | refreshing... reason: update_tabs
20220107T182200.956571Z |    DEBUG | util.profiler | HistoryModel.refresh 0.0000
20220107T182200.967571Z |    DEBUG | util.profiler | AddressList.update 0.0000
20220107T182200.967571Z |    DEBUG | util.profiler | AssetList.update 0.0000
20220107T182214.120324Z |     INFO | plugins.trezor.clientbase.TrezorClientBase | timed out`

**Comment by chk777** [comment]
I wrote a code snippet from device initialization and initialization completion,
where actually there are errors

**Comment by Electrum-RVN-SIG** [comment]
One of our devs says

"The This is something I have been hunting for a long time. Its also with other coins on electrum -- there seem to be some timeout for the Trezor bridge, but I have no idea why and where this could be fixed. My observation is that with Linux it works better in general, but it also depends on the exact Trezor bridge and Trezor FW.
Its best to try with a single tx (signature) first, so select only one tx. This usually worked for me -- more than 10 never worked."

Try sending less at a time or go into view > show coins and select <10 to spend

**Comment by chk777** [comment]
I was patched to send 10 coins and only one transaction

**Comment by kralverde** [comment]
could you let me know if it works or fails?

**Comment by chk777** [comment]
unfortunately not working

**Comment by kralverde** [comment]
were you mining to your hardware at all?
