### ISSUE TITLE
Electrum can not pair with your Trezor

### ISSUE THREAD

**Issue by MitrilGM** [Electrum-RVN-SIG/electrum-ravencoin#37]
When I try to pay transaction (clicking on the "Pay" button) I got regular dialog box about "Enter your current Trezor PIN". Then I can see quickly "Singing transaction" dialog and "Enter Passphrase" dialog to unlock wallet. 

When I successfully finished entering passphrase, I got "Check your Trezor device to continue". I confirmed this on Trezor twice but always got a message from title "Electrum can not pair with your Trezor". 

Any help or suggestions? 

![TrezorCantPair](https://user-images.githubusercontent.com/4127601/149659343-fec96032-cfb5-4cbd-830b-247211a703e4.png)

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v0.4.5

**Comment by MitrilGM** [comment]
Thank you for your effort. Everything works fine with new version.
