### ISSUE TITLE
cannot send assets

### ISSUE THREAD

**Issue by ghost** [Electrum-RVN-SIG/electrum-ravencoin#38]
no options . using 0.3.0 original ravencoin electrum installed client .. i dont know if there was an update to support this or not . 
if not it could be as easy as adding the asset name and amount to the send page instead of just the normal RVN amount on send page.

reason being i want to send a token to another user .

double posting issue to other forks

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v0.4.4

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v0.4.5
