### ISSUE TITLE
Electrum Ravencoin 0.4.5 you can compile to Python 3.8 please?

### ISSUE THREAD

**Issue by chk777** [Electrum-RVN-SIG/electrum-ravencoin#39]
this version is good but it won't run under win7 and it's not even about the msi-api. many users still have win7

**Comment by kralverde** [comment]
Unfortunately, the trezor api requires this new version of python, but you should just be able to run the run_electrum.py with your local python without the need for a binary file (after pip installing the requirements). (https://github.com/spesmilo/electrum/issues/5976) you can use these prebuilts if you trust me and don't want to build your own https://github.com/Electrum-RVN-SIG/prebuilts/tree/master/dll
