### ISSUE TITLE
Ledger nano x won't open wallet 0.2.2

### ISSUE THREAD

**Issue by OversizedWizard** [Electrum-RVN-SIG/electrum-ravencoin#4]
Installed version 0.3.0.

When it starts, I point it to my ledger wallet from version 0.2.2 and click next then the app just shuts down.

Only way to open app, was to create a new wallet.

Then I could open my old wallet file from within the app interface but my original mining address is gone. Will I still get paid to that original address?

**Comment by kralverde** [comment]
Yes. Everything is tied to your ledger device. In your electrum folder there are log files. Could you find the error in there?

**Comment by OversizedWizard** [comment]
20210610T142311.529388Z |     INFO | simple_config.SimpleConfig | electrum directory C:\Users\jason\AppData\Roaming\Electrum-Ravencoin
20210610T142311.532391Z |     INFO | logging | Electrum version: 0.3.0 - https://electrum.org - https://github.com/Electrum-RVN-SIG/electrum-ravencoin
20210610T142311.532391Z |     INFO | logging | Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]. On platform: Windows-10-10.0.19041-SP0
20210610T142311.533392Z |     INFO | logging | Logging to file: C:\Users\jason\AppData\Roaming\Electrum-Ravencoin\logs\electrum_log_20210610T142311Z_19840.log
20210610T142311.533392Z |     INFO | logging | Log filters: verbosity '', verbosity_shortcuts ''
20210610T142311.538397Z |     INFO | plugin.Plugins | registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
20210610T142311.538397Z |     INFO | plugin.Plugins | registering hardware trezor: ('hardware', 'trezor', 'Trezor wallet')
20210610T142311.567422Z |     INFO | plugin.Plugins | loaded virtualkeyboard
20210610T142311.567422Z |    DEBUG | util.profiler | Plugins.__init__ 0.0340
20210610T142311.568423Z |     INFO | network | blockchains [0]
20210610T142311.568423Z |     INFO | exchange_rate.FxThread | using exchange CoinGecko
20210610T142311.570425Z |     INFO | network | starting network
20210610T142311.570425Z |    DEBUG | util.profiler | Daemon.__init__ 0.0030
20210610T142311.571426Z |     INFO | daemon.Daemon | launching GUI: qt
20210610T142311.575430Z |     INFO | network | setting proxy None
20210610T142311.575430Z |     INFO | network | connecting to electrum1.rvn.rocks:50002:s as new interface
20210610T142311.576431Z |     INFO | daemon.Daemon | starting taskgroup.
20210610T142311.576431Z |     INFO | network | starting taskgroup.
20210610T142311.577431Z |     INFO | exchange_rate.CoinGecko | getting fx quotes for GBP
20210610T142311.734573Z |     INFO | gui.qt.history_list | could not import electrum.plot. This feature needs matplotlib to be installed.
20210610T142311.745583Z |     INFO | gui.qt.ElectrumGui | Qt GUI starting up... Qt=5.15.2, PyQt=5.15.4
20210610T142311.932753Z |    DEBUG | util.profiler | ElectrumGui.__init__ 0.1872
20210610T142311.932753Z |     INFO | storage.WalletStorage | wallet path d:\desktop\electrum-rvn_data\wallets\myrvnledger_wallet
20210610T142312.267559Z |     INFO | exchange_rate.CoinGecko | received fx quotes
20210610T142312.274565Z |     INFO | storage.WalletStorage | wallet path d:\desktop\electrum-rvn_data\wallets\myrvnledger_wallet
20210610T142312.281572Z |     INFO | interface.[electrum3.rvn.rocks:50002] | connection established. version: ['ElectrumX Ravencoin 1.8', '1.8']
20210610T142312.298587Z |     INFO | interface.[electrum1.rvn.rocks:50002] | connection established. version: ['ElectrumX Ravencoin 1.8', '1.8']
20210610T142312.322609Z |     INFO | interface.[electrum2.rvn.rocks:50002] | connection established. version: ['ElectrumX Ravencoin 1.8', '1.8']
20210610T142312.330616Z |     INFO | interface.[electrum1.rvn.rocks:50002] | set blockchain with height 18144
20210610T142312.330616Z |     INFO | interface.[electrum1.rvn.rocks:50002] | can't connect 1792342
20210610T142312.330616Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting block header 18145 in mode backward
20210610T142312.331617Z |     INFO | network | switching to electrum1.rvn.rocks:50002:s
20210610T142312.334620Z |     INFO | interface.[electrum3.rvn.rocks:50002] | set blockchain with height 18144
20210610T142312.365648Z |     INFO | network | fee_estimates {25: 1000000, 10: 1000000, 5: 1000000, 2: 1000000}
20210610T142312.374656Z |     INFO | interface.[electrum2.rvn.rocks:50002] | set blockchain with height 18144
20210610T142312.398678Z |     INFO | network | fee_histogram []
20210610T142312.399678Z |     INFO | interface.[electrum1.rvn.rocks:50002] | exiting backward mode at 18145
20210610T142312.400679Z |     INFO | interface.[electrum1.rvn.rocks:50002] | could connect 18145
20210610T142312.401680Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 18146
20210610T142312.893124Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 20162
20210610T142313.286988Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 22178
20210610T142313.680852Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 24194
20210610T142314.082213Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 26210
20210610T142314.492087Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 28226
20210610T142314.945497Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 30242
20210610T142314.946498Z |     INFO | interface.[rvn4lyfe.com:50002] | disconnecting due to: ConnectError(ConnectionRefusedError(10061, "Connect call failed ('51.222.139.25', 50002)"),)
20210610T142314.947499Z |     INFO | network | couldn't launch iface rvn4lyfe.com:50002:s -- CancelledError()
20210610T142315.397905Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 32258
20210610T142315.398907Z |     INFO | interface.[143.198.142.78:50002] | disconnecting due to: ErrorGettingSSLCertFromServer(ConnectError(ConnectionRefusedError(10061, "Connect call failed ('143.198.142.78', 50002)"),),)
20210610T142315.399907Z |     INFO | network | couldn't launch iface 143.198.142.78:50002:s -- CancelledError()
20210610T142315.786341Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 34274
20210610T142316.179697Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 36290
20210610T142316.604285Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 38306
20210610T142317.026169Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 40322
20210610T142317.473573Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 42338
20210610T142317.876938Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 44354
20210610T142318.276299Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 46370
20210610T142318.711692Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 48386
20210610T142319.155092Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 50402
20210610T142319.601495Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 52418
20210610T142320.047898Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 54434
20210610T142320.491299Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 56450
20210610T142320.938704Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 58466
20210610T142321.380102Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 60482
20210610T142321.832510Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 62498
20210610T142322.279916Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 64514
20210610T142322.727319Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 66530
20210610T142323.171720Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 68546
20210610T142323.617123Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 70562
20210610T142324.063526Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 72578
20210610T142324.513933Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 74594
20210610T142324.955332Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 76610
20210610T142325.400734Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 78626
20210610T142325.841132Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 80642
20210610T142326.287535Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 82658
20210610T142326.741945Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 84674
20210610T142327.179341Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 86690
20210610T142327.626745Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 88706
20210610T142328.075150Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 90722
20210610T142328.534564Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 92738
20210610T142328.976965Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 94754
20210610T142329.418363Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 96770
20210610T142329.860763Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 98786
20210610T142330.301160Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 100802
20210610T142330.742559Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 102818
20210610T142331.181956Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 104834
20210610T142331.624356Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 106850
20210610T142332.058748Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 108866
20210610T142332.487134Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 110882
20210610T142332.881492Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 112898
20210610T142333.269843Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 114914
20210610T142333.648690Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 116930
20210610T142334.046554Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 118946
20210610T142334.435906Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 120962
20210610T142334.821253Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 122978
20210610T142335.201596Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 124994
20210610T142335.625980Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 127010
20210610T142336.066379Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 129026
20210610T142336.530797Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 131042
20210610T142336.991213Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 133058
20210610T142337.433613Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 135074
20210610T142337.825967Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 137090
20210610T142338.205310Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 139106
20210610T142338.596166Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 141122
20210610T142338.980514Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 143138
20210610T142339.365863Z |     INFO | storage.WalletStorage | wallet path c:\users\jason\appdata\roaming\electrum-ravencoin\wallets\myrvnledger_wallet
20210610T142339.368866Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 145154
20210610T142339.777234Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 147170
20210610T142340.172592Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 149186
20210610T142340.568950Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 151202
20210610T142340.942286Z |     INFO | wallet_db.WalletDB | upgrading wallet format
20210610T142341.040374Z |     INFO | interface.[electrum1.rvn.rocks:50002] | requesting chunk from height 153218
20210610T142341.044378Z |    ERROR | daemon.Daemon | GUI raised exception: AssertionError(). shutting down.
20210610T142341.044378Z |     INFO | daemon.Daemon | on_stop() entered. initiating shutdown
20210610T142341.045379Z |     INFO | gui.qt.ElectrumGui | closing GUI
20210610T142341.045379Z |     INFO | daemon.Daemon | stopping all wallets
20210610T142341.045379Z |     INFO | daemon.Daemon | stopping network and taskgroup
20210610T142341.045379Z |     INFO | network | stopping network
20210610T142341.046380Z |     INFO | daemon.Daemon | taskgroup stopped.
20210610T142341.100429Z |     INFO | interface.[electrum3.rvn.rocks:50002] | disconnecting due to: CancelledError()
20210610T142341.101429Z |     INFO | interface.[electrum2.rvn.rocks:50002] | disconnecting due to: CancelledError()
20210610T142341.111439Z |     INFO | interface.[electrum1.rvn.rocks:50002] | disconnecting due to: CancelledError()
20210610T142341.111439Z |     INFO | network | taskgroup stopped.
20210610T142341.112440Z |     INFO | daemon.Daemon | removing lockfile
20210610T142341.112440Z |     INFO | daemon.Daemon | stopped
20210610T142341.112440Z |    ERROR | __main__ | daemon.run_gui errored
Traceback (most recent call last):
  File "run_electrum", line 411, in handle_cmd
  File "electrum\daemon.py", line 579, in run_gui
  File "electrum\gui\qt\__init__.py", line 414, in main
  File "electrum\gui\qt\__init__.py", line 291, in wrapper
  File "electrum\gui\qt\__init__.py", line 316, in start_new_window
  File "electrum\gui\qt\__init__.py", line 361, in _start_wizard_to_select_or_create_wallet
  File "electrum\wallet_db.py", line 74, in __init__
  File "electrum\wallet_db.py", line 107, in load_data
  File "electrum\util.py", line 519, in <lambda>
  File "electrum\util.py", line 514, in do_profile
  File "electrum\wallet_db.py", line 193, in upgrade
  File "electrum\wallet_db.py", line 841, in _convert_version_41
  File "electrum\util.py", line 519, in <lambda>
  File "electrum\util.py", line 514, in do_profile
  File "electrum\wallet_db.py", line 1305, in _load_transactions
  File "electrum\json_db.py", line 79, in __init__
  File "electrum\json_db.py", line 44, in wrapper
  File "electrum\json_db.py", line 105, in __setitem__
  File "electrum\wallet_db.py", line 1348, in _convert_dict
  File "electrum\wallet_db.py", line 1348, in <genexpr>
  File "electrum\invoices.py", line 111, in from_json
  File "<attrs generated init electrum.invoices.OnchainInvoice>", line 8, in __init__
    self.outputs = __attr_converter_outputs(outputs)
  File "electrum\invoices.py", line 71, in _decode_outputs
  File "electrum\transaction.py", line 224, in from_legacy_tuple
  File "electrum\transaction.py", line 192, in from_address_and_value
  File "electrum\transaction.py", line 1655, in __init__
  File "electrum\transaction.py", line 185, in __init__
AssertionError
20210610T142341.142467Z |     INFO | plugin.Plugins | stopped
First log file of 0.3.0

I don't know what I'm looking for

**Comment by kralverde** [comment]
I see the problem, thank you for the help. This will be fixed in the next update. For now creating a "new" wallet again with your ledger or re-entering your seed words if its a software wallet will allow to make the jump from 0.2.2 to 0.3.0

**Comment by OversizedWizard** [comment]
thanks glad to help identifying. issue

**Comment by kralverde** [comment]
Patched in https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/5ada603a76f684280b6172768060626583c8d7d1
Will close after public testing of 0.4.0 ends
