### ISSUE TITLE
Error when signing transaction on MacOS

### ISSUE THREAD

**Issue by lisandroScofano** [Electrum-RVN-SIG/electrum-ravencoin#53]
Hi, I'm getting the attached issue when trying to sign a transaction. I am running Electrum in MacOS. I tried closing and re-opening but did not work.

<img width="757" alt="Screen Shot 2022-09-04 at 15 14 25" src="https://user-images.githubusercontent.com/6107281/188327779-b9c69ab5-be75-4298-8f72-3aae0b4d60aa.png">
<img width="728" alt="Screen Shot 2022-09-04 at 15 14 46" src="https://user-images.githubusercontent.com/6107281/188327787-3e2ef8c8-8981-47af-8381-73e37c892444.png">

**Comment by kralverde** [comment]
60e1a61a8705358ac438ec77a66bc59d96d3b79c

this should fix it, ill come out with a pre-release and ask you to confirm
