### ISSUE TITLE
broken IPFS links 

### ISSUE THREAD

**Issue by MangoFarmAssets** [Electrum-RVN-SIG/electrum-ravencoin#55]
I noticed using Electrum-RVN today that the asset IPFS links were broken.  They go to an https site that no longer has SSL.  I wanted to point it out.  

You are welcome to use the RavencoinIPFS gateway https://ravencoinipfs-gateway.com/IPFS/<hash> if you want.

Electrum worked great btw.

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/f0fba0c39bed231dd7cd005086b1a41689cf591b

**Comment by kralverde** [comment]
You can also change the ipfs gateway from settings
