### ISSUE TITLE
Python 3.9 does not work with x16r et al

### ISSUE THREAD

**Issue by Buccaneer69** [Electrum-RVN-SIG/electrum-ravencoin#64]
Maybe you should mention that one should use python 3.8 instead.

**Comment by kralverde** [comment]
The associated GitHub for x16r and x16rv2 have the updated cpython, but the pypi is not updated. I've been debating whether to use the raw GitHub, creating a new pypi, or just leaving x16r/v2 blocks optional, failing to "unverified" since they're legacy

**Comment by kralverde** [comment]
went with just having the git hash in the requirements
