### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\UTILISATEUR\\AppData\\Local\\Temp\\_MEI31322\\electrum\\wordlist\\spanish.txt'

### ISSUE THREAD

**Issue by Electrum-RVN-SIG** [Electrum-RVN-SIG/electrum-ravencoin#69]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
Traceback (most recent call last):
  File "electrum\gui\qt\seed_dialog.py", line 366, in on_edit
  File "electrum\mnemonic.py", line 170, in __init__
  File "electrum\mnemonic.py", line 132, in from_file
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\UTILISATEUR\\AppData\\Local\\Temp\\_MEI31322\\electrum\\wordlist\\spanish.txt'

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\UTILISATEUR\\AppData\\Local\\Temp\\_MEI31322\\electrum\\wordlist\\spanish.txt'
```

Reporter
------------

This issue was reported by 2 user(s):

| Electrum-Ravencoin Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 1.0.0  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.19045-SP0 | imported | en_GB | [ℹ](https://crashhub.rvn4lyfe.com//crash/3) | 
| 1.2.3  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.19045-SP0 | standard | en_SE | [ℹ](https://crashhub.rvn4lyfe.com//crash/38) | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v1.0.1

**Comment by Electrum-RVN-SIG** [comment]
Good afternoon @kralverde,

I just received another crash report related to this issue. The crash occured on Electrum-Ravencoin 1.2.3.
I'm not sure which versions of Electrum-Ravencoin include the fix but this is the first report from anything
newer than 1.0.0 since you closed the issue.

Could you please check if this issue really is resolved? Here is the traceback that I just collected:

```Python traceback
Traceback (most recent call last):
  File "electrum\gui\qt\main_window.py", line 132, in onPress
  File "electrum\gui\qt\main_window.py", line 160, in request_password
  File "electrum\gui\qt\main_window.py", line 2094, in show_seed_dialog
  File "electrum\gui\qt\seed_dialog.py", line 515, in __init__
  File "electrum\gui\qt\seed_dialog.py", line 230, in __init__
  File "electrum\mnemonic.py", line 170, in __init__
  File "electrum\mnemonic.py", line 132, in from_file
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\anon\\AppData\\Local\\Temp\\_MEI87122\\electrum\\wordlist\\english.txt'

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\anon\\AppData\\Local\\Temp\\_MEI87122\\electrum\\wordlist\\english.txt'
```


~ _With robotic wishes_

**Comment by kralverde** [comment]
I tried to re-create with all 3 windows exe's and could not reproduce. Could whoever made this comment follow up with more information, e.g. what you were doing when this happened

**Comment by kralverde** [comment]
I am also unsure of why it is in a "temp" directory.
