### ISSUE TITLE
Improper address generation

### ISSUE THREAD

**Issue by Electrum-RVN-SIG** [Electrum-RVN-SIG/electrum-ravencoin#7]
address derivation m/44/175/0 is only for ledger. Normal generation should use m/44/1/0. Need to implement correct derivation and add a back-port option when generating a wallet from words for users who want to import words from a past version.

**Comment by Electrum-RVN-SIG** [comment]
44/175 is the BIP44 derivation.
44/1 is the BIP39 derviation, what the core wallets use.
Implement a search for both in the scan accounts button

**Comment by kralverde** [comment]
No, 44/175 is the correct derivation; 44/1 is the test net derivation. Implement this.
