### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Electrum-RVN-SIG** [Electrum-RVN-SIG/electrum-ravencoin#70]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
Traceback (most recent call last):
  File "/tmp/.mount_electrdw0lw1/usr/lib/python3.10/site-packages/electrum/gui/qt/broadcast_view_tab.py", line 269, in watch_asset
    if get_error_for_asset_typed(asset, AssetType.OWNER) and get_error_for_asset_typed(asset, AssetType.MSG_CHANNEL):
  File "/tmp/.mount_electrdw0lw1/usr/lib/python3.10/site-packages/electrum/asset.py", line 180, in get_error_for_asset_typed
    if asset[-1] != ASSET_OWNER_IDENTIFIER:
IndexError: string index out of range

IndexError: string index out of range
```

Reporter
------------

This issue was reported by 2 user(s):

| Electrum-Ravencoin Version  | Python Version | Operating System  | Wallet Type  | Locale | Stack |
|---|---|---|---|---|---|
| 1.0.2  | 3.10.11 (main, Jun 28 2018, 19:01:02) [GCC 8.3.0] | Linux-5.11.0-27-generic-x86_64-with-glibc2.31 | standard | en_US | [ℹ](https://crashhub.rvn4lyfe.com//crash/4) | 
| 1.0.2  | 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit (Intel)] | Windows-10-10.0.22621-SP0 | standard | en_US | [ℹ](https://crashhub.rvn4lyfe.com//crash/5) | 

Additional Information
------------------------

> On the Broadcast tab, hit the "Watch Asset" button with no asset name entered

---

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/22e9c5bc76231517cc98ed90151eba688dc196a4

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v1.1.0
