### ISSUE TITLE
Electrum-ravencoin 1.0.2 does not work on Win10

### ISSUE THREAD

**Issue by NeuraiProject** [Electrum-RVN-SIG/electrum-ravencoin#71]
**Version:** Electrum Ravencoin 1.0.2 (all versions)
**SO:** Windows 10 Home or PRO
**Virtualbox:** 7.0.10 r158379

I have installed a clean version of windows 10 in Virtualbox and **Electrum Ravencoin 1.0.2** does not even start. If I run the debug version I get this error: 

```
C:\Program Files (x86)\Electrum Ravencoin>electrum-ravencoin-v1.0.2-debug.exe
x16r, x16rv2 and kawpow modules are required
```

If I install **Microsoft Visual C++ Redistributable packages** x86 it works.

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

Direct URL:    https://aka.ms/vs/17/release/vc_redist.x86.exe

I have tried both windows 10 Home and PRO version with the same result. If Microsoft Redistributable packages are not installed in the OS, it does not work.

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/b94f7afa43ac7e80e319cb25d9359e3891dbc1c5

**Comment by NeuraiProject** [comment]
Thanks.
