### ISSUE TITLE
error with ledger nano s

### ISSUE THREAD

**Issue by xtraperlo** [Electrum-RVN-SIG/electrum-ravencoin#72]
hi:
after update from 0.52 version to 1.1.0, says version is old version and don't open wallet
thanks

**Comment by kralverde** [comment]
Hi, you need to recreate your wallet with the new version. See [the version 1.0.0 release](https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v1.0.1) for more information but you just need to create a new wallet with your ledger. All addresses will be the same.

**Comment by xtraperlo** [comment]
i try...
thanks kralverde
