### ISSUE TITLE
Version 3, cannot even connect to Ledger

### ISSUE THREAD

**Issue by slapshotkc** [Electrum-RVN-SIG/electrum-ravencoin#9]
![image](https://user-images.githubusercontent.com/85588428/122803520-577d0e80-d28c-11eb-9f3e-e3abee4bf6e3.png)
I tried creating a new wallet, version 3 still cannot access my ledger.  Tried a different USB cable as well, I simply get this error.  Is there anyway to go back to version 2.2 or am I screwed?

**Comment by kralverde** [comment]
https://github.com/kralverde/electrum-raven/releases/tag/v0.2.2

Make sure your ledger is unlocked and you are in the ravencoin app.

Would you mind sending me your log file?

**Comment by slapshotkc** [comment]
All good, removed Ravencoin app from ledger and re-installed.  Connected and Synced up just fine with 0.3.0.  Thank you.

**Comment by kralverde** [comment]
Alright, glad to hear. Closing this issue.
