### ISSUE TITLE
Trezor hardware wallet Unsupported models

### ISSUE THREAD

**Issue by Refloow** [Electrum-RVN-SIG/electrum-ravencoin#91]
There seems to be an issue with trezor safe 3. Electrum plugin need updating to recognize the model
![image](https://github.com/Electrum-RVN-SIG/electrum-ravencoin/assets/59449926/ac7d34b0-18cd-46b8-930c-989b1c466b18)

**Comment by Refloow** [comment]
Additional information, ive used latest release 1.2.3
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v1.2.3
on windows

**Comment by Refloow** [comment]
bitcoin seems to have addressed the issue already, here is the commit
https://github.com/spesmilo/electrum/commit/6172898a035e6ccbe5e8c85a34bc2f14acd106b3

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/commit/23acf0f5aca1398dbd459272379e4a59d5eba216

**Comment by kralverde** [comment]
https://github.com/Electrum-RVN-SIG/electrum-ravencoin/releases/tag/v1.2.4
