### ISSUE TITLE
Trezor Safe 5  is not supported

### ISSUE THREAD

**Issue by Toshimichi0915** [Electrum-RVN-SIG/electrum-ravencoin#92]
![image](https://github.com/user-attachments/assets/4bd5be8a-7ff9-427f-a558-184a5a86d705)

version: 1.2.4 (the latest version as of 2024-08-31)

**Comment by kralverde** [comment]
Hi, the master branch has support for trezor5, but I'm waiting for the upstream electrum to fix their build script so I can make new binaries

**Comment by kralverde** [comment]
A signed build for windows is available in the discord if you'd like to use it

**Comment by Toshimichi0915** [comment]
Unfortunately I'm on arch Linux 😭
I cloned the repo , and got the app to run as expected but I can't build the image due to Docker errors (I couldn't find the cause of it, and am still searching for it)

**Comment by Toshimichi0915** [comment]
Never mind. I got successful build after reboot.
Which build script fails currently? (just curious)

P. S. It seems like the build needs [this patch](https://github.com/spesmilo/electrum/pull/9141/commits/8ae2a7868e41f03ca56eeef729375440d91c191c) as well as some other fixes

![image](https://github.com/user-attachments/assets/37f80eee-21ba-4476-8dec-198f5976f482)

(The error seems total nonsense to me, after which I found out the error message was actually caused by an internal error, not by library version mismatch)

**Comment by kralverde** [comment]
You can just run ./electrum-env you don't even need a docker, but I'll take a look at the patch, thank you. I did get verification from another user that it did work so it's a bit odd. (It's the Mac build script that is failing)

**Comment by kralverde** [comment]
That patch should be implemented, could you try running natively? You might have to source into the env to install the hw requirements

**Comment by Toshimichi0915** [comment]
https://github.com/Toshimichi0915/electrum-ravencoin-pr
It's working fine for now (There are many unused imports and I'm not sure if they will cause issue at some point)

> could you try running natively? 

I'm not entirely sure what this means. I modified a little bit of the code, but that's about it.

**Comment by kralverde** [comment]
Would you like to make a PR?

**Comment by Toshimichi0915** [comment]
Sure thing

**Comment by kralverde** [comment]
Merged, very odd, I thought I did this already. Maybe it's in a different branch... thank you!
